In [1]:
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
df = pd.read_csv(r'C:\Users\Rodrigo Lapsky\Documents\Dados\DataSets\Pizza\pizza_sales.csv')

In [3]:
print(df.shape)
df.head(15)

(48620, 12)

,pizza_id,order_id,pizza_name_id,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name
0,1.0,1.0,hawaiian_m,1.0,1/1/2015,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza
1,2.0,2.0,classic_dlx_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza
2,3.0,2.0,five_cheese_l,1.0,1/1/2015,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza
3,4.0,2.0,ital_supr_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
4,5.0,2.0,mexicana_m,1.0,1/1/2015,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza
5,6.0,2.0,thai_ckn_l,1.0,1/1/2015,11:57:40,20.75,20.75,L,Chicken,"Chicken, Pineapple, Tomatoes, Red Peppers, Tha...",The Thai Chicken Pizza
6,7.0,3.0,ital_supr_m,1.0,1/1/2015,12:12:28,16.50,16.50,M,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
7,8.0,3.0,prsc_argla_l,1.0,1/1/2015,12:12:28,20.75,20.75,L,Supreme,"Prosciutto di San Daniele, Arugula, Mozzarella...",The Prosciutto and Arugula Pizza
8,9.0,4.0,ital_supr_m,1.0,1/1/2015,12:16:31,16.50,16.50,M,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
9,10.0,5.0,ital_supr_m,1.0,1/1/2015,12:21:30,16.50,16.50,M,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza
10,11.0,6.0,bbq_ckn_s,1.0,1/1/2015,12:29:36,12.75,12.75,S,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",The Barbecue Chicken Pizza
11,12.0,6.0,the_greek_s,1.0,1/1/2015,12:29:36,12.00,12.00,S,Classic,"Kalamata Olives, Feta Cheese, Tomatoes, Garlic...",The Greek Pizza
12,13.0,7.0,spinach_supr_s,1.0,1/1/2015,12:50:37,12.50,12.50,S,Supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",The Spinach Supreme Pizza
13,14.0,8.0,spinach_supr_s,1.0,1/1/2015,12:51:37,12.50,12.50,S,Supreme,"Spinach, Red Onions, Pepperoni, Tomatoes, Arti...",The Spinach Supreme Pizza
14,15.0,9.0,classic_dlx_s,1.0,1/1/2015,12:52:01,12.00,12.00,S,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza

In [4]:
print(df.duplicated().sum())
print(df.isnull().sum())

0
pizza_id             0
order_id             0
pizza_name_id        0
quantity             0
order_date           0
order_time           0
unit_price           0
total_price          0
pizza_size           0
pizza_category       0
pizza_ingredients    0
pizza_name           0
dtype: int64

In [5]:
df = df.drop(columns=['pizza_id','pizza_name_id','order_id'])

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   quantity           48620 non-null  float64
 1   order_date         48620 non-null  object
 2   order_time         48620 non-null  object
 3   unit_price         48620 non-null  float64
 4   total_price        48620 non-null  float64
 5   pizza_size         48620 non-null  object
 6   pizza_category     48620 non-null  object
 7   pizza_ingredients  48620 non-null  object
 8   pizza_name         48620 non-null  object
dtypes: float64(3), object(6)
memory usage: 3.3+ MB

In [7]:
for i in df.columns:
    print(f"column: {i}")
    print(df[i].unique())
    print("-" * 30)

column: quantity
[1. 2. 3. 4.]
------------------------------
column: order_date
['1/1/2015' '2/1/2015' '3/1/2015' '4/1/2015' '5/1/2015' '6/1/2015'
 '7/1/2015' '8/1/2015' '9/1/2015' '10/1/2015' '11/1/2015' '12/1/2015'
 '13-01-2015' '14-01-2015' '15-01-2015' '16-01-2015' '17-01-2015'
 '18-01-2015' '19-01-2015' '20-01-2015' '21-01-2015' '22-01-2015'
 '23-01-2015' '24-01-2015' '25-01-2015' '26-01-2015' '27-01-2015'
 '28-01-2015' '29-01-2015' '30-01-2015' '31-01-2015' '1/2/2015' '2/2/2015'
 '3/2/2015' '4/2/2015' '5/2/2015' '6/2/2015' '7/2/2015' '8/2/2015'
 '9/2/2015' '10/2/2015' '11/2/2015' '12/2/2015' '13-02-2015' '14-02-2015'
 '15-02-2015' '16-02-2015' '17-02-2015' '18-02-2015' '19-02-2015'
 '20-02-2015' '21-02-2015' '22-02-2015' '23-02-2015' '24-02-2015'
 '25-02-2015' '26-02-2015' '27-02-2015' '28-02-2015' '1/3/2015' '2/3/2015'
 '3/3/2015' '4/3/2015' '5/3/2015' '6/3/2015' '7/3/2015' '8/3/2015'
 '9/3/2015' '10/3/2015' '11/3/2015' '12/3/2015' '13-03-2015' '14-03-2015'
 '15-03-2015' '16-03-2015' '17-03-2015' '18-03-2015' '19-03-2015'
 '20-03-2015' '21-03-2015' '22-03-2015' '23-03-2015' '24-03-2015'
 '25-03-2015' '26-03-2015' '27-03-2015' '28-03-2015' '29-03-2015'
 '30-03-2015' '31-03-2015' '1/4/2015' '2/4/2015' '3/4/2015' '4/4/2015'
 '5/4/2015' '6/4/2015' '7/4/2015' '8/4/2015' '9/4/2015' '10/4/2015'
 '11/4/2015' '12/4/2015' '13-04-2015' '14-04-2015' '15-04-2015'
 '16-04-2015' '17-04-2015' '18-04-2015' '19-04-2015' '20-04-2015'
 '21-04-2015' '22-04-2015' '23-04-2015' '24-04-2015' '25-04-2015'
 '26-04-2015' '27-04-2015' '28-04-2015' '29-04-2015' '30-04-2015'
 '1/5/2015' '2/5/2015' '3/5/2015' '4/5/2015' '5/5/2015' '6/5/2015'
 '7/5/2015' '8/5/2015' '9/5/2015' '10/5/2015' '11/5/2015' '12/5/2015'
 '13-05-2015' '14-05-2015' '15-05-2015' '16-05-2015' '17-05-2015'
 '18-05-2015' '19-05-2015' '20-05-2015' '21-05-2015' '22-05-2015'
 '23-05-2015' '24-05-2015' '25-05-2015' '26-05-2015' '27-05-2015'
 '28-05-2015' '29-05-2015' '30-05-2015' '31-05-2015' '1/6/2015' '2/6/2015'
 '3/6/2015' '4/6/2015' '5/6/2015' '6/6/2015' '7/6/2015' '8/6/2015'
 '9/6/2015' '10/6/2015' '11/6/2015' '12/6/2015' '13-06-2015' '14-06-2015'
 '15-06-2015' '16-06-2015' '17-06-2015' '18-06-2015' '19-06-2015'
 '20-06-2015' '21-06-2015' '22-06-2015' '23-06-2015' '24-06-2015'
 '25-06-2015' '26-06-2015' '27-06-2015' '28-06-2015' '29-06-2015'
 '30-06-2015' '1/7/2015' '2/7/2015' '3/7/2015' '4/7/2015' '5/7/2015'
 '6/7/2015' '7/7/2015' '8/7/2015' '9/7/2015' '10/7/2015' '11/7/2015'
 '12/7/2015' '13-07-2015' '14-07-2015' '15-07-2015' '16-07-2015'
 '17-07-2015' '18-07-2015' '19-07-2015' '20-07-2015' '21-07-2015'
 '22-07-2015' '23-07-2015' '24-07-2015' '25-07-2015' '26-07-2015'
 '27-07-2015' '28-07-2015' '29-07-2015' '30-07-2015' '31-07-2015'
 '1/8/2015' '2/8/2015' '3/8/2015' '4/8/2015' '5/8/2015' '6/8/2015'
 '7/8/2015' '8/8/2015' '9/8/2015' '10/8/2015' '11/8/2015' '12/8/2015'
 '13-08-2015' '14-08-2015' '15-08-2015' '16-08-2015' '17-08-2015'
 '18-08-2015' '19-08-2015' '20-08-2015' '21-08-2015' '22-08-2015'
 '23-08-2015' '24-08-2015' '25-08-2015' '26-08-2015' '27-08-2015'
 '28-08-2015' '29-08-2015' '30-08-2015' '31-08-2015' '1/9/2015' '2/9/2015'
 '3/9/2015' '4/9/2015' '5/9/2015' '6/9/2015' '7/9/2015' '8/9/2015'
 '9/9/2015' '10/9/2015' '11/9/2015' '12/9/2015' '13-09-2015' '14-09-2015'
 '15-09-2015' '16-09-2015' '17-09-2015' '18-09-2015' '19-09-2015'
 '20-09-2015' '21-09-2015' '22-09-2015' '23-09-2015' '26-09-2015'
 '27-09-2015' '28-09-2015' '29-09-2015' '30-09-2015' '1/10/2015'
 '2/10/2015' '3/10/2015' '4/10/2015' '6/10/2015' '7/10/2015' '8/10/2015'
 '9/10/2015' '10/10/2015' '11/10/2015' '13-10-2015' '14-10-2015'
 '15-10-2015' '16-10-2015' '17-10-2015' '18-10-2015' '20-10-2015'
 '21-10-2015' '22-10-2015' '23-10-2015' '24-10-2015' '25-10-2015'
 '27-10-2015' '28-10-2015' '29-10-2015' '30-10-2015' '31-10-2015'
 '1/11/2015' '2/11/2015' '3/11/2015' '4/11/2015' '5/11/2015' '6/11/2015'
 '7/11/2015' '8/11/2015' '9/11/2015' '10/11/2015' '11/11/2015'
 '12/11/2015' '13-11-2015' '14-11-2015' '15-11-2015' '16-11-2015'
 '17-11-2015' '18-11-2015' '19-11-2015' '20-11-2015' '21-11-2015'
 '22-11-2015' '23-11-2015' '24-11-2015' '25-11-2015' '26-11-2015'
 '27-11-2015' '28-11-2015' '29-11-2015' '30-11-2015' '1/12/2015'
 '2/12/2015' '3/12/2015' '4/12/2015' '5/12/2015' '6/12/2015' '7/12/2015'
 '8/12/2015' '9/12/2015' '10/12/2015' '11/12/2015' '12/12/2015'
 '13-12-2015' '14-12-2015' '15-12-2015' '16-12-2015' '17-12-2015'
 '18-12-2015' '19-12-2015' '20-12-2015' '21-12-2015' '22-12-2015'
 '23-12-2015' '24-12-2015' '26-12-2015' '27-12-2015' '28-12-2015'
 '29-12-2015' '30-12-2015' '31-12-2015']
------------------------------
column: order_time
['11:38:36' '11:57:40' '12:12:28' ... '20:51:07' '21:14:37' '22:09:54']
------------------------------
column: unit_price
[13.25 16.   18.5  20.75 16.5  12.75 12.   12.5  20.5  20.25 16.75 15.25
 17.95 16.25 14.75  9.75 17.5  10.5  25.5  11.   14.5  12.25 21.   23.65
 35.95]
------------------------------
column: total_price
[13.25 16.   18.5  20.75 16.5  12.75 12.   12.5  20.5  20.25 16.75 15.25
 17.95 16.25 14.75 32.    9.75 17.5  10.5  25.5  11.   14.5  12.25 21.
 62.25 41.5  50.25 23.65 24.   33.5  35.9  25.   19.5  37.5  37.   41.
 33.   40.5  24.5  47.3  22.   35.95 29.   29.5  26.5  48.75 32.5  30.5
 48.   51.   36.   35.   83.   61.5  49.5  55.5 ]
------------------------------
column: pizza_size
['M' 'L' 'S' 'XL' 'XXL']
------------------------------
column: pizza_category
['Classic' 'Veggie' 'Supreme' 'Chicken']
------------------------------
column: pizza_ingredients
['Sliced Ham, Pineapple, Mozzarella Cheese'
 'Pepperoni, Mushrooms, Red Onions, Red Peppers, Bacon'
 'Mozzarella Cheese, Provolone Cheese, Smoked Gouda Cheese, Romano Cheese, Blue Cheese, Garlic'
 'Calabrese Salami, Capocollo, Tomatoes, Red Onions, Green Olives, Garlic'
 'Tomatoes, Red Peppers, Jalapeno Peppers, Red Onions, Cilantro, Corn, Chipotle Sauce, Garlic'
 'Chicken, Pineapple, Tomatoes, Red Peppers, Thai Sweet Chilli Sauce'
 'Prosciutto di San Daniele, Arugula, Mozzarella Cheese'
 'Barbecued Chicken, Red Peppers, Green Peppers, Tomatoes, Red Onions, Barbecue Sauce'
 'Kalamata Olives, Feta Cheese, Tomatoes, Garlic, Beef Chuck Roast, Red Onions'
 'Spinach, Red Onions, Pepperoni, Tomatoes, Artichokes, Kalamata Olives, Garlic, Asiago Cheese'
 'Spinach, Mushrooms, Tomatoes, Green Olives, Feta Cheese'
 'Capocollo, Red Peppers, Tomatoes, Goat Cheese, Garlic, Oregano'
 'Capocollo, Tomatoes, Goat Cheese, Artichokes, Peperoncini verdi, Garlic'
 'Spinach, Artichokes, Tomatoes, Sun-dried Tomatoes, Garlic, Pesto Sauce'
 'Mushrooms, Tomatoes, Red Peppers, Green Peppers, Red Onions, Zucchini, Spinach, Garlic'
 'Chicken, Tomatoes, Red Peppers, Red Onions, Jalapeno Peppers, Corn, Cilantro, Chipotle Sauce'
 'Chicken, Artichoke, Spinach, Garlic, Jalapeno Peppers, Fontina Cheese, Gouda Cheese'
 'Mozzarella Cheese, Pepperoni'
 'Chicken, Tomatoes, Red Peppers, Spinach, Garlic, Pesto Sauce'
 'Bacon, Pepperoni, Italian Sausage, Chorizo Sausage'
 'Soppressata Salami, Fontina Cheese, Mozzarella Cheese, Mushrooms, Garlic'
 'Ricotta Cheese, Gorgonzola Piccante Cheese, Mozzarella Cheese, Parmigiano Reggiano Cheese, Garlic'
 'Tomatoes, Anchovies, Green Olives, Red Onions, Garlic'
 '?duja Salami, Pancetta, Tomatoes, Red Onions, Friggitello Peppers, Garlic'
 'Eggplant, Artichokes, Tomatoes, Zucchini, Red Peppers, Garlic, Pesto Sauce'
 'Spinach, Artichokes, Kalamata Olives, Sun-dried Tomatoes, Feta Cheese, Plum Tomatoes, Red Onions'
 'Genoa Salami, Capocollo, Pepperoni, Tomatoes, Asiago Cheese, Garlic'
 'Spinach, Mushrooms, Red Onions, Feta Cheese, Garlic'
 'Coarse Sicilian Salami, Tomatoes, Green Olives, Luganega Sausage, Onions, Garlic'
 'Chicken, Red Onions, Red Peppers, Mushrooms, Asiago Cheese, Alfredo Sauce'
 'Pepperoni, Mushrooms, Green Peppers'
 'Brie Carre Cheese, Prosciutto, Caramelized Onions, Pears, Thyme, Garlic']
------------------------------
column: pizza_name
['The Hawaiian Pizza' 'The Classic Deluxe Pizza' 'The Five Cheese Pizza'
 'The Italian Supreme Pizza' 'The Mexicana Pizza' 'The Thai Chicken Pizza'
 'The Prosciutto and Arugula Pizza' 'The Barbecue Chicken Pizza'
 'The Greek Pizza' 'The Spinach Supreme Pizza' 'The Green Garden Pizza'
 'The Italian Capocollo Pizza' 'The Spicy Italian Pizza'
 'The Spinach Pesto Pizza' 'The Vegetables + Vegetables Pizza'
 'The Southwest Chicken Pizza' 'The California Chicken Pizza'
 'The Pepperoni Pizza' 'The Chicken Pesto Pizza' 'The Big Meat Pizza'
 'The Soppressata Pizza' 'The Four Cheese Pizza' 'The Napolitana Pizza'
 'The Calabrese Pizza' 'The Italian Vegetables Pizza'
 'The Mediterranean Pizza' 'The Pepper Salami Pizza'
 'The Spinach and Feta Pizza' 'The Sicilian Pizza'
 'The Chicken Alfredo Pizza' 'The Pepperoni, Mushroom, and Peppers Pizza'
 'The Brie Carre Pizza']
------------------------------

In [8]:
df['order_date'] = pd.to_datetime(df['order_date'], dayfirst=True, format='mixed')
df['month'] = df['order_date'].dt.month_name()

In [9]:
df['estimated_profit'] = df['total_price'] * 0.60

In [10]:
df.head()

,quantity,order_date,order_time,unit_price,total_price,pizza_size,pizza_category,pizza_ingredients,pizza_name,month,estimated_profit
0,1.0,2015-01-01,11:38:36,13.25,13.25,M,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",The Hawaiian Pizza,January,7.95
1,1.0,2015-01-01,11:57:40,16.00,16.00,M,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",The Classic Deluxe Pizza,January,9.60
2,1.0,2015-01-01,11:57:40,18.50,18.50,L,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",The Five Cheese Pizza,January,11.10
3,1.0,2015-01-01,11:57:40,20.75,20.75,L,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",The Italian Supreme Pizza,January,12.45
4,1.0,2015-01-01,11:57:40,16.00,16.00,M,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",The Mexicana Pizza,January,9.60

In [12]:
df.to_csv('pizza.csv',index=False,sep=';',decimal=',',encoding='utf-8-sig')